### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by justis5** [dungthai85/CompWorlds491#9]
If you lose and get the "Game Over" screen, you can press the "Back" button and the "Game Over" options still remain. If you press the "Play again" button, you get a screen with the bars for elixir and hp on the screen still on the menu screen. 
![image](https://user-images.githubusercontent.com/37807886/74470514-8cd14b00-4e53-11ea-9898-cb75dd7526ae.png)
![image](https://user-images.githubusercontent.com/37807886/74470541-9d81c100-4e53-11ea-9300-b680a05cf1ee.png)

**Comment by dungthai85** [comment]
Solved
